title: vov's blog
email: master.vov.me@gmail.com
description: "초보 아빠의 좌충우돌 육아이야기 입니다."
base_url: ""
url: "http://blog.vov.me"
author :
  name : vov
  email : master.vov.me@gmail.com

encoding: utf-8
excerpt_separator : <!--more-->
tags_dir: tags
categories_dir: categories

paginate: 5

google_analytics : 'UA-31506558-5'

#twitter_username: saltfactory
#github_username:  saltfactory
#facebook_username: salthub
#facebook_admins_id: "1825058169"
#facebook_app_id: "271162092926857"
#disqus_shortname: saltfactoryblog

comments:
  disqus: true
  facebook: true

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough"]

# highlighter: pygments
permalink: none

# safe: false # if using alias is safe:false
#safe: true
#lsi: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-feed
  # - jekyll-img-converter
  # - jekyll-coffeescript
